# Generated by Django 4.0.2 on 2022-05-05 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0002_cursus_student_comments_student_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursus',
            options={'verbose_name_plural': 'Cursus'},
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(help_text='tell why the student is missing', max_length=255, null=True, verbose_name='reason')),
                ('is_missing', models.BooleanField()),
                ('date', models.DateField(verbose_name='date of call')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lycee.student')),
            ],
        ),
    ]
