# Generated by Django 4.0.2 on 2022-05-22 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0003_alter_cursus_options_presence'),
    ]

    operations = [
        migrations.AddField(
            model_name='presence',
            name='cursus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lycee.cursus'),
        ),
        migrations.AlterField(
            model_name='presence',
            name='is_missing',
            field=models.BooleanField(default=True, verbose_name='Is Missing'),
        ),
        migrations.AlterField(
            model_name='presence',
            name='reason',
            field=models.CharField(default='', help_text='tell why the student is missing', max_length=255, verbose_name='reason'),
        ),
        migrations.RemoveField(
            model_name='presence',
            name='student',
        ),
        migrations.AddField(
            model_name='presence',
            name='student',
            field=models.ManyToManyField(to='lycee.Student'),
        ),
        migrations.CreateModel(
            name='ParticularPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date of call')),
                ('is_missing', models.BooleanField(verbose_name='Is Missing')),
                ('reason', models.CharField(default='', help_text="Raison de l'absence", max_length=255, verbose_name='Reason')),
                ('cursus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lycee.cursus')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lycee.student')),
            ],
        ),
    ]
